const PETS={'golden-retriever':'金毛','corgi':'柯基','shiba':'柴犬','husky':'哈士奇','samoyed':'萨摩耶','border-collie':'边牧','labrador':'拉布拉多','poodle':'贵宾犬','bichon':'比熊','schnauzer':'雪纳瑞','westie':'西高地','french-bulldog':'法斗','orange-cat':'橘猫','black-cat':'黑猫','white-tiger':'白虎','tabby-cat':'狸花猫','tiger-striped-cat':'虎斑猫','calico-cat':'三花猫','ragdoll-cat':'布偶猫','garfield':'加菲猫','golden-cat':'金猫','silver-cat':'银猫','rabbit':'小白兔','angora-rabbit':'安哥拉兔','curl-ear-rabbit':'垂耳兔','panda':'熊猫','red-panda':'小熊猫','capybara':'水豚','polar-bear':'北极熊','pig':'小猪','lamb':'小羊','horse':'小马','llama':'羊驼','monkey':'小猴','chick':'小鸡','parrot':'鹦鹉','koel-duck':'柯尔鸭','leopard':'小豹子','tiger':'小老虎','unicorn':'独角兽','nine-tail-fox':'九尾狐','azure-dragon':'青龙','vermilion-bird':'朱雀','pixiu':'貔貅','suanni':'狻猊','succulent-spirit':'多肉精灵','blue-cat':'蓝猫'};
const LEVELS=[['破壳新生',30],['蹒跚学步',100],['活力萌宠',220],['贴心伙伴',400],['家庭明星',650],['守护精灵',950],['奇迹伙伴',1350],['幸福传说',1850]],COST={feed:2,play:2,clean:1,rest:0};
const DEFAULT={version:5,pet:{type:'golden-retriever',name:'金毛',xp:0,adopted:false,hunger:76,mood:82,clean:68,energy:72,lastTick:Date.now()},members:[{id:'m3',name:'小宇',emoji:'👦',hearts:12}],tasks:[{id:'t1',title:'读英语20分钟',memberId:'m3',reward:5,doneDate:''},{id:'t2',title:'阅读30分钟',memberId:'m3',reward:5,doneDate:''}],history:[],sound:true};
let state=load();const $=s=>document.querySelector(s),day=()=>new Date().toLocaleDateString('sv-SE'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return {...structuredClone(DEFAULT),...JSON.parse(localStorage.getItem('family-pet-v1'))}}catch{return structuredClone(DEFAULT)}}function save(){localStorage.setItem('family-pet-v1',JSON.stringify(state))}function level(){let n=0;LEVELS.forEach((x,i)=>{if(state.pet.xp>=x[1])n=i});return n}function tick(){let h=Math.min(48,(Date.now()-(state.pet.lastTick||Date.now()))/36e5);if(h>.25){for(const[k,r]of[['hunger',1.3],['mood',.45],['clean',.7],['energy',.55]])state.pet[k]=Math.max(0,state.pet[k]-h*r);state.pet.lastTick=Date.now()}}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1700)}function ding(){if(!state.sound)return;let c=new AudioContext,o=c.createOscillator(),g=c.createGain();o.connect(g).connect(c.destination);o.frequency.value=560;g.gain.value=.05;o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.2);o.stop(c.currentTime+.2)}function weekly(id){let since=Date.now()-6048e5;return state.history.filter(h=>h.memberId===id&&new Date(h.date)>=since).reduce((a,h)=>a+h.reward,0)}
function render(){tick();let l=level(),next=LEVELS[l+1],p=state.pet,start=LEVELS[l][1],end=next?.[1]||start+500;$('#petName').textContent=p.name;$('#levelBadge').textContent=`Lv.${l+1} ${LEVELS[l][0]}`;$('#petImage').src=`assets/pets/${p.type}/${l+1}.webp`;$('#xpBar').style.width=Math.min(100,(p.xp-start)/(end-start)*100)+'%';$('#xpText').textContent=next?`${p.xp} / ${next[1]}`:`${p.xp} / MAX`;for(const k of['hunger','mood','clean','energy']){$(`#${k}Bar`).style.width=p[k]+'%';$(`#${k}Text`).textContent=Math.round(p[k])}$('#memberList').innerHTML=state.members.map(m=>`<div class="member"><span class="avatar">${m.emoji}</span><div><b>${esc(m.name)}</b><small>本周贡献 ${weekly(m.id)} 点</small></div><span class="hearts">${m.hearts} ❤️</span></div>`).join('');$('#taskList').innerHTML=state.tasks.map(t=>{let m=state.members.find(x=>x.id===t.memberId)||{name:'全家',emoji:'🏡'},done=t.doneDate===day();return `<div class="task ${done?'done':''}"><button class="check" data-task="${t.id}">${done?'✓':''}</button><div><span class="task-name">${esc(t.title)}</span><small>${m.emoji} ${esc(m.name)}</small></div><span class="reward">+${t.reward} ❤️</span></div>`}).join('');$('#todayPoints').textContent=state.history.filter(h=>h.date===day()).reduce((a,h)=>a+h.reward,0)+' ❤️';$('#nextUnlock').textContent=next?`Lv.${l+2} ${next[0]}`:'已到最高等级';$('#nextHint').textContent=next?`还差 ${next[1]-p.xp} 成长值，解锁新形态`:'你们共同创造了幸福传说！';$('#todayText').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());petOptions();save()}
function petOptions(){if(!$('#petSelect').options.length)$('#petSelect').innerHTML=Object.entries(PETS).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');$('#petSelect').value=state.pet.type;$('#petPreview').innerHTML=Array.from({length:8},(_,i)=>`<img src="assets/pets/${state.pet.type}/${i+1}.webp" title="Lv.${i+1}">`).join('')}
function care(a){let m=[...state.members].sort((a,b)=>b.hearts-a.hearts)[0],p=state.pet;if(!m)return toast('请先添加家庭成员');if(m.hearts<COST[a])return toast('爱心不够，先完成任务吧');m.hearts-=COST[a];if(a==='feed'){p.hunger=Math.min(100,p.hunger+22);p.xp+=3}if(a==='play'){p.mood=Math.min(100,p.mood+24);p.energy=Math.max(0,p.energy-8);p.xp+=4}if(a==='clean'){p.clean=Math.min(100,p.clean+30);p.xp+=3}if(a==='rest'){p.energy=Math.min(100,p.energy+25);p.xp++}ding();toast(`${m.name} 照顾了 ${p.name}`);render()}
function complete(id){let t=state.tasks.find(x=>x.id===id);if(!t||t.doneDate===day())return;let m=state.members.find(x=>x.id===t.memberId);if(m)m.hearts+=t.reward;t.doneDate=day();state.pet.xp+=t.reward*2;state.history.push({date:day(),taskId:id,memberId:t.memberId,reward:t.reward});ding();toast(`完成任务，获得 ${t.reward} 颗爱心`);render()}
function migrateToXiaoyu(){if((state.version||1)>=2)return;state.members=state.members.filter(m=>!['爸爸','妈妈'].includes(m.name)).map(m=>m.id==='m3'?{...m,name:'小宇',emoji:'👦'}:m);if(!state.members.length)state.members=structuredClone(DEFAULT.members);state.tasks=state.tasks.filter(t=>state.members.some(m=>m.id===t.memberId));state.version=2;save()}
migrateToXiaoyu();
function migrateEggRule(){if((state.version||1)>=3)return;state.pet.adopted=state.pet.xp>0;state.version=3;save()}
migrateEggRule();
function migrateDefaultTasks(){if((state.version||1)>=4)return;let oldDefaults=['收拾自己的房间','整理书桌','完成今日阅读','洗好晚餐的碗','给阳台的花浇水'];state.tasks=state.tasks.filter(t=>!oldDefaults.includes(t.title));if(!state.tasks.some(t=>t.title==='读英语20分钟'))state.tasks.unshift(structuredClone(DEFAULT.tasks[0]));if(!state.tasks.some(t=>t.title==='阅读30分钟'))state.tasks.splice(1,0,structuredClone(DEFAULT.tasks[1]));if(!state.pet.adopted||state.pet.name==='团团')state.pet.name=PETS[state.pet.type]||'萌宠';state.version=4;save()}
migrateDefaultTasks();
function migrateReadingReward(){if((state.version||1)>=5)return;state.tasks.filter(t=>t.title==='阅读30分钟').forEach(t=>t.reward=5);state.version=5;save()}
migrateReadingReward();
function addDeleteButtons(){
  [...document.querySelectorAll('#memberList .member')].forEach((row,index)=>{if(row.querySelector('[data-delete-member]'))return;let member=state.members[index];if(!member)return;let button=document.createElement('button');button.className='delete-item';button.dataset.deleteMember=member.id;button.title=`删除家庭成员 ${member.name}`;button.setAttribute('aria-label',button.title);button.textContent='×';row.append(button)});
  [...document.querySelectorAll('#taskList .task')].forEach((row,index)=>{if(row.querySelector('[data-delete-task]'))return;let task=state.tasks[index];if(!task)return;let button=document.createElement('button');button.className='delete-item';button.dataset.deleteTask=task.id;button.title=`删除任务 ${task.title}`;button.setAttribute('aria-label',button.title);button.textContent='×';row.append(button)});
  [...document.querySelectorAll('#memberList .member')].forEach((row,index)=>{let member=state.members[index],avatar=row.querySelector('.avatar');if(member?.name==='小宇'&&avatar&&!avatar.querySelector('img'))avatar.innerHTML='<img src="assets/icons/avatar-xiaoyu.svg" alt="小宇头像">'});
  [...document.querySelectorAll('#memberList .member')].forEach((row,index)=>{let member=state.members[index],avatar=row.querySelector('.avatar');if(member?.name!=='小宇'&&avatar&&!avatar.classList.contains('initial-avatar')){avatar.textContent=(member?.name||'家').slice(0,1);avatar.className=`avatar initial-avatar avatar-${member?.emoji||'mint'}`}});
  [...document.querySelectorAll('#memberList .member')].forEach(row=>{let hearts=row.querySelector('.hearts');if(hearts&&!hearts.querySelector('img'))hearts.innerHTML=`<span>${hearts.textContent.replace(/[^0-9]/g,'')}</span><img src="assets/icons/heart.svg" alt="爱心">`});
  [...document.querySelectorAll('#taskList .task')].forEach((row,index)=>{let member=state.members.find(m=>m.id===state.tasks[index]?.memberId),info=row.querySelector('small'),reward=row.querySelector('.reward');if(member?.name==='小宇'&&info&&!info.querySelector('img'))info.innerHTML='<img src="assets/icons/avatar-xiaoyu.svg" alt="小宇头像"><span>小宇</span>';if(reward&&!reward.querySelector('img'))reward.innerHTML=`<span>${reward.textContent.replace(/[^+0-9]/g,'')}</span><img src="assets/icons/heart.svg" alt="爱心">`});
}
function deleteMember(id){let member=state.members.find(m=>m.id===id);if(!member)return;let assigned=state.tasks.filter(t=>t.memberId===id).length,message=`确定删除家庭成员“${member.name}”吗？`;if(assigned)message+=`\n同时会删除分配给该成员的 ${assigned} 项任务。`;message+='\n已经获得的成长值和历史记录会保留。';if(!confirm(message))return;state.members=state.members.filter(m=>m.id!==id);state.tasks=state.tasks.filter(t=>t.memberId!==id);save();render();toast(`已删除成员 ${member.name}`)}
function deleteTask(id){let task=state.tasks.find(t=>t.id===id);if(!task||!confirm(`确定删除任务“${task.title}”吗？\n已经获得的爱心和成长值不会倒扣。`))return;state.tasks=state.tasks.filter(t=>t.id!==id);save();render();toast('任务已删除')}
let deleteStyle=document.createElement('style');deleteStyle.textContent='.member,.task{position:relative;padding-right:34px}.delete-item{position:absolute;right:5px;top:50%;transform:translateY(-50%);width:25px;height:25px;padding:0!important;border:0!important;border-radius:50%!important;background:transparent!important;color:#b5a79a;font-size:20px;line-height:23px}.delete-item:hover{background:#fee7e2!important;color:#c85f55}.avatar{overflow:hidden}.avatar img{display:block;width:100%;height:100%;object-fit:cover}.initial-avatar{color:#fff;font-size:18px;font-weight:bold}.avatar-mint{background:#75b894}.avatar-sky{background:#6daed0}.avatar-peach{background:#e99572}.avatar-lavender{background:#9989ce}.avatar-sun{background:#dfa947}';document.head.append(deleteStyle);
new MutationObserver(addDeleteButtons).observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{let memberId=e.target.closest('[data-delete-member]')?.dataset.deleteMember,taskId=e.target.closest('[data-delete-task]')?.dataset.deleteTask;if(memberId){e.preventDefault();e.stopPropagation();deleteMember(memberId)}if(taskId){e.preventDefault();e.stopPropagation();deleteTask(taskId)}},true);
const normalRender=render;render=function(){normalRender();let egg=!state.pet.adopted||state.pet.xp<30;$('#adoptBtn').hidden=state.pet.adopted;if(egg){$('#petImage').src='assets/pets/egg.webp';$('#levelBadge').textContent=state.pet.adopted?'🥚 孵化中':'🥚 等待领养';$('#xpBar').style.width=Math.min(100,state.pet.xp/30*100)+'%';$('#xpText').textContent=`${state.pet.xp} / 30`;$('#nextUnlock').textContent='孵化出第一形态';$('#nextHint').textContent=state.pet.adopted?`还差 ${Math.max(0,30-state.pet.xp)} 成长值，完成任务帮助破壳`:'先点击宠物蛋进行领养';$('#petSpeech').textContent=state.pet.adopted?'蛋壳里传来了轻轻的心跳…':'小宇，领养这颗神秘宠物蛋吧！'}else{$('#petSpeech').textContent='今天也要一起加油呀！'}};
const normalCare=care;care=function(action){if(!state.pet.adopted)return toast('请先领养宠物蛋');if(state.pet.xp<30)return toast('宠物还在蛋里，完成任务可积累孵化成长值');normalCare(action)};
const normalComplete=complete;complete=function(id){if(!state.pet.adopted)return toast('请先领养宠物蛋，再完成任务');normalComplete(id)};
let adoptBtn=document.createElement('button');adoptBtn.id='adoptBtn';adoptBtn.textContent='🐣 进入领养中心';adoptBtn.onclick=()=>openAdoption();document.querySelector('.stage').append(adoptBtn);
let adoptionSelected=state.pet.type||'golden-retriever',adoptionDialog=document.createElement('dialog');adoptionDialog.id='adoptionDialog';adoptionDialog.className='adoption-dialog';adoptionDialog.innerHTML='<form method="dialog"><div class="adoption-head"><div><h3>🐣 领养一只萌宠</h3><p>选择喜欢的宠物，给它起个名字。领养后会先得到一颗蛋。</p></div><button value="cancel" aria-label="关闭">×</button></div><div id="adoptionGallery" class="adoption-gallery"></div><label class="pet-name-label">给萌宠取名<input id="adoptionName" maxlength="10" placeholder="例如：团团"></label><div class="adoption-summary"><img id="adoptionChoiceImage" alt="已选择的宠物"><span>已选择：<b id="adoptionChoiceName"></b><small>确认后从宠物蛋开始孵化</small></span></div><div class="adoption-actions"><button value="cancel">暂不领养</button><button type="button" id="confirmAdoption" class="primary">确认领养</button></div></form>';document.body.append(adoptionDialog);
function renderAdoptionGallery(){document.querySelector('#adoptionGallery').innerHTML=Object.entries(PETS).map(([type,name])=>`<button type="button" class="pet-choice ${type===adoptionSelected?'selected':''}" data-pet-choice="${type}"><img src="assets/pets/${type}/1.webp" alt="${name}"><span>${name}</span></button>`).join('');document.querySelector('#adoptionChoiceImage').src=`assets/pets/${adoptionSelected}/1.webp`;document.querySelector('#adoptionChoiceName').textContent=PETS[adoptionSelected]}
function openAdoption(){adoptionSelected=state.pet.type||'golden-retriever';document.querySelector('#adoptionName').value=state.pet.adopted?state.pet.name:PETS[adoptionSelected];renderAdoptionGallery();adoptionDialog.showModal()}
document.querySelector('#adoptionGallery').onclick=e=>{let choice=e.target.closest('[data-pet-choice]');if(!choice)return;adoptionSelected=choice.dataset.petChoice;document.querySelector('#adoptionName').value=PETS[adoptionSelected];renderAdoptionGallery()};
document.querySelector('#confirmAdoption').onclick=()=>{let name=document.querySelector('#adoptionName').value.trim();if(!name)return toast('请先给萌宠取一个名字');if(state.pet.adopted&&!confirm(`重新领养会让“${state.pet.name}”的成长进度从宠物蛋开始，确定继续吗？`))return;state.pet={...state.pet,type:adoptionSelected,name:name.slice(0,10),xp:0,adopted:true,hunger:76,mood:82,clean:68,energy:72,lastTick:Date.now()};save();adoptionDialog.close();ding();render();toast(`成功领养 ${name}，现在是一颗等待孵化的蛋！`)};
let adoptionEntry=document.createElement('button');adoptionEntry.id='adoptionEntry';adoptionEntry.textContent='🐣 领养宠物';adoptionEntry.onclick=openAdoption;document.querySelector('header>div:last-child').prepend(adoptionEntry);
document.querySelectorAll('.panel .title h2')[1].textContent='今日任务';
let brand=document.querySelector('.brand');brand.innerHTML='<img class="brand-home" src="assets/icons/home.svg" alt="家园"><span>小宇的萌宠乐园</span>';
if(document.querySelector('.total'))document.querySelector('.total').style.display='none';
let gardenGround=document.querySelectorAll('.stage>div')[1];gardenGround.className='garden-ground';gardenGround.innerHTML='<img class="garden-decor" src="assets/icons/garden-decor.svg" alt="花园">';let unlock=document.querySelector('.unlock'),unlockText=[...unlock.childNodes].find(n=>n.nodeType===3);if(unlockText)unlockText.remove();unlock.insertAdjacentHTML('afterbegin','<span class="unlock-title"><img src="assets/icons/gift.svg" alt="礼物">下一级解锁</span>');let detailIconStyle=document.createElement('style');detailIconStyle.textContent='.brand{display:flex;align-items:center;gap:8px}.brand-home{width:34px;height:34px}.garden-ground{position:absolute;bottom:0;left:0;right:0}.garden-decor{display:block;width:min(520px,90%);height:72px;object-fit:contain;margin:auto}.hearts,.reward{display:flex;align-items:center;gap:4px}.hearts img,.reward img{width:22px;height:22px}.task small{display:flex;align-items:center;gap:5px}.task small img{width:24px;height:24px;border-radius:50%}.unlock-title{display:flex;align-items:center;gap:8px;font-size:16px}.unlock-title img{width:27px;height:27px}';document.head.append(detailIconStyle);
const controlHelp={hunger:['饱食','宠物会随时间变饿；点击喂食可以恢复饱食'],mood:['心情','宠物心情会随时间下降；点击玩耍可以恢复心情'],clean:['清洁','清洁度会随时间下降；点击清洁可以恢复'],energy:['精力','精力会随时间下降，玩耍也会消耗精力；点击休息可以恢复']};Object.entries(controlHelp).forEach(([id,[name,help]])=>{let bar=document.querySelector(`#${id}Bar`)?.closest('div');if(bar){bar.title=help;bar.setAttribute('aria-label',`${name}：${help}`)}});const careHelp={feed:'消耗2颗爱心：饱食增加22，成长值增加3',play:'消耗2颗爱心：心情增加24、精力减少8，成长值增加4',clean:'消耗1颗爱心：清洁增加30，成长值增加3',rest:'免费：精力增加25，成长值增加1'};Object.entries(careHelp).forEach(([action,help])=>{let button=document.querySelector(`[data-action="${action}"]`);button.title=help;button.setAttribute('aria-label',help)});let cleanButton=document.querySelector('[data-action="clean"]');cleanButton.innerHTML='🧼<b>清洁</b><small>−1 爱心</small>';
document.querySelector('#petSelect').addEventListener('change',e=>{e.preventDefault();e.stopImmediatePropagation();e.target.value=state.pet.type;document.querySelector('#settingsDialog').close();openAdoption()},true);
let growthRules=document.createElement('div');growthRules.className='growth-rules';growthRules.innerHTML='<h4>成长加减规则</h4><ul><li><b>领养：</b>从神秘宠物蛋开始，30 成长值后孵化。</li><li><b>完成任务：</b>获得任务标注的爱心；成长值增加“爱心奖励 × 2”。</li><li><b>喂食：</b>−2 爱心，饱食 +22，成长 +3。</li><li><b>玩耍：</b>−2 爱心，心情 +24、精力 −8，成长 +4。</li><li><b>清洁：</b>−1 爱心，清洁 +30，成长 +3。</li><li><b>休息：</b>不消耗爱心，精力 +25，成长 +1。</li><li><b>自然变化：</b>每小时饱食 −1.3、清洁 −0.7、精力 −0.55、心情 −0.45，最低为 0。</li><li><b>成长阶段：</b>蛋（0）→ Lv.1（30）→ Lv.2（100）→ Lv.3（220）→ Lv.4（400）→ Lv.5（650）→ Lv.6（950）→ Lv.7（1350）→ Lv.8（1850）。</li><li><b>删除：</b>删除任务或成员不会倒扣已经获得的爱心和成长值。</li></ul>';document.querySelector('#settingsDialog form').insertBefore(growthRules,document.querySelector('#settingsDialog .notice'));
let growthStyle=document.createElement('style');growthStyle.textContent='#adoptBtn{position:absolute;z-index:3;bottom:34px;border:0;border-radius:24px;padding:11px 18px;background:#f1a353;color:white;font-weight:bold;box-shadow:0 7px 18px #9b673c44}#adoptBtn[hidden]{display:none}#adoptionEntry{color:#a56625;background:#fff5dd;border-color:#edce98}.adoption-dialog{width:min(780px,94vw);max-height:90vh}.adoption-dialog form{padding:22px}.adoption-head{display:flex;justify-content:space-between;align-items:flex-start}.adoption-head h3{margin:0 0 5px}.adoption-head p{margin:0;color:#8c8177;font-size:12px}.adoption-head>button{border:0;background:transparent;font-size:24px;color:#9b8e82;padding:0}.adoption-gallery{display:grid!important;grid-template-columns:repeat(auto-fill,minmax(82px,1fr));gap:9px;max-height:390px;overflow:auto;margin:18px 0!important;padding:4px}.pet-choice{display:flex;flex-direction:column;align-items:center;gap:5px;border:2px solid transparent;border-radius:13px;padding:7px 4px;background:#f8f4eb;color:#554c44}.pet-choice img{width:65px;height:65px;object-fit:contain}.pet-choice span{font-size:11px}.pet-choice:hover{background:#fff0d8}.pet-choice.selected{border-color:#ef9f4f;background:#fff4dd;box-shadow:0 3px 12px #b77b3728}.pet-name-label{font-weight:bold}.pet-name-label input{font-weight:normal}.adoption-summary{display:flex!important;align-items:center;gap:10px;margin:10px 0!important;padding:9px 12px;border-radius:12px;background:#eef7e8}.adoption-summary img{width:55px;height:55px;object-fit:contain}.adoption-summary span{display:flex;flex-direction:column}.adoption-summary small{color:#8c8177;margin-top:3px}.adoption-actions{display:flex!important;justify-content:flex-end;gap:9px;margin-top:14px!important}.growth-rules{margin:12px 0;padding:12px 15px;border-radius:12px;background:#eef7e8}.growth-rules h4{margin:0 0 7px}.growth-rules ul{margin:0;padding-left:19px;font-size:12px;line-height:1.65}.growth-rules li+li{margin-top:3px}@media(max-width:600px){.adoption-gallery{grid-template-columns:repeat(4,1fr);max-height:330px}.pet-choice img{width:52px;height:52px}#adoptionEntry{font-size:0}#adoptionEntry:after{content:"🐣";font-size:19px}}';document.head.append(growthStyle);
const iconPath=name=>`assets/icons/${name}.svg`,iconHtml=(name,label)=>`<img class="ui-icon" src="${iconPath(name)}" alt=""><span>${label}</span>`;function applyPrettyIcons(){let sound=$('#soundBtn'),settings=$('#settingsBtn'),entry=$('#adoptionEntry');if(sound&&!sound.querySelector('img'))sound.innerHTML=`<img class="header-icon" src="${iconPath('sound')}" alt="声音">`;if(settings&&!settings.querySelector('img'))settings.innerHTML=`<img class="header-icon" src="${iconPath('settings')}" alt="设置">`;if(entry&&!entry.querySelector('img'))entry.innerHTML=iconHtml('egg','领养宠物');let statIcons={hunger:['food','饱食'],mood:['mood','心情'],clean:['clean','清洁'],energy:['energy','精力']};Object.entries(statIcons).forEach(([id,[icon,label]])=>{let row=$(`#${id}Bar`)?.closest('div');if(row&&!row.querySelector('.ui-icon')){let text=[...row.childNodes].find(n=>n.nodeType===3);if(text)text.remove();row.insertAdjacentHTML('afterbegin',iconHtml(icon,label))}});let actions={feed:['food','喂食','−2 爱心'],play:['play','玩耍','−2 爱心'],clean:['clean','清洁','−1 爱心'],rest:['rest','休息','免费']};Object.entries(actions).forEach(([action,[icon,label,cost]])=>{let button=document.querySelector(`[data-action="${action}"]`);if(button&&!button.querySelector('.action-icon'))button.innerHTML=`<img class="action-icon" src="${iconPath(icon)}" alt=""><b>${label}</b><small>${cost}</small>`});if(adoptBtn&&!adoptBtn.querySelector('img'))adoptBtn.innerHTML=iconHtml('egg','进入领养中心')};let iconStyle=document.createElement('style');iconStyle.textContent='.ui-icon{width:24px;height:24px;object-fit:contain;vertical-align:middle}.stats>div{grid-template-columns:24px 36px 1fr 28px}.header-icon{width:23px;height:23px;display:block}.action-icon{display:block;width:38px;height:38px;margin:0 auto 3px}.care button{font-size:inherit}.care button:hover .action-icon{transform:translateY(-2px) scale(1.05)}.action-icon{transition:.2s}#adoptionEntry,#adoptBtn{display:inline-flex;align-items:center;justify-content:center;gap:7px}#adoptionEntry .ui-icon{width:22px;height:22px}@media(max-width:600px){#adoptionEntry{font-size:0!important}#adoptionEntry:after{content:none!important}#adoptionEntry .ui-icon{width:23px;height:23px}}';document.head.append(iconStyle);applyPrettyIcons();new MutationObserver(applyPrettyIcons).observe(document.querySelector('header'),{childList:true,subtree:true});
document.onclick=e=>{let a=e.target.closest('[data-action]')?.dataset.action,id=e.target.closest('[data-task]')?.dataset.task;if(a)care(a);if(id)complete(id)};$('#addMemberBtn').onclick=()=>$('#memberDialog').showModal();$('#saveMember').onclick=e=>{let n=$('#memberName').value.trim();if(!n)return e.preventDefault();state.members.push({id:'m'+Date.now(),name:n,emoji:$('#memberEmoji').value,hearts:10});$('#memberName').value='';render()};$('#addTaskBtn').onclick=()=>{if(!state.members.length)return toast('请先添加家庭成员');$('#taskMember').innerHTML=state.members.map(m=>`<option value="${m.id}">${m.emoji} ${esc(m.name)}</option>`);$('#taskDialog').showModal()};$('#saveTask').onclick=e=>{let n=$('#taskTitle').value.trim();if(!n)return e.preventDefault();state.tasks.push({id:'t'+Date.now(),title:n,memberId:$('#taskMember').value,reward:Math.max(1,Math.min(20,+$('#taskReward').value||1)),doneDate:''});$('#taskTitle').value='';render()};$('#renamePetBtn').onclick=()=>{let n=prompt('给宠物起个新名字：',state.pet.name);if(n?.trim()){state.pet.name=n.trim().slice(0,10);render()}};$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'🔊':'🔇';save()};$('#settingsBtn').onclick=()=>{$('#settingsDialog').showModal();petOptions()};$('#petSelect').onchange=e=>{state.pet.type=e.target.value;render()};
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`家庭电子宠物-${day()}.json`;a.click();URL.revokeObjectURL(a.href);toast('备份已导出')}$('#exportBtn').onclick=$('#quickExport').onclick=exportData;$('#importFile').onchange=async e=>{try{let d=JSON.parse(await e.target.files[0].text());if(!d.pet||!Array.isArray(d.members))throw 0;state=d;render();toast('数据导入成功')}catch{toast('备份文件无效')}};$('#resetBtn').onclick=()=>{if(confirm('确定恢复初始数据吗？')){state=structuredClone(DEFAULT);render()}};setInterval(render,60000);$('#soundBtn').textContent=state.sound?'🔊':'🔇';render();
